<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Spatial weights objects as sparse matrices and graphs}
-->
# Spatial weights objects as sparse matrices and graphs
======================================================
This vignette shows how.

```{r}
library(sp)
library(spdep)
library(maptools)
columbus <- readShapePoly(system.file("etc/shapes/columbus.shp", package="spdep")[1])
nb_q <- poly2nb(columbus)
coords <- coordinates(columbus)
```

```{r}
col2 <- droplinks(nb_q, 21)
plot(nb_q, coords, col="grey")
plot(col2, coords, add=TRUE)
```

```{r}
res <- n.comp.nb(col2)
table(res$comp.id)
```


```{r}
nb_B <- nb2listw(col2, style="B", zero.policy=TRUE)
B <- as(nb_B, "symmetricMatrix")
nb_B1 <- mat2listw(as(B, "dgTMatrix"))
all.equal(nb_B1$neighbours, col2)
```


```{r}
n <- nrow(B)
I <- Diagonal(n)
rho <- 0.1
c(determinant(I - rho * B, logarithm=TRUE)$modulus)
sum(log(1 - rho * eigenw(nb_B)))
nW <- -B
nChol <- Cholesky(nW, Imult=8)
n * log(rho) + (2 * c(determinant(update(nChol, nW, 1/rho))$modulus))
```



```{r}
nb_W <- nb2listw(col2, style="W", zero.policy=TRUE)
W <- as(nb_W, "CsparseMatrix")
n <- nrow(W)
set.seed(1)
x <- runif(n)
r1 <- as.numeric(W %*% x)
r2 <- lag(nb_W, x, zero.policy=TRUE)
all.equal(r1, r2, check.attributes=FALSE)
```



```{r}
I <- Diagonal(n)
rho <- 0.5
LU <- lu(I - rho * W)
sum(log(abs(diag(slot(LU, "U")))))
sum(log(1 - rho * eigenw(nb_W)))
```


```{r}
class(B)
object.size(B)
library(igraph)
g1 <- graph.adjacency(B, mode="undirected")
class(g1)
object.size(g1)
```


```{r}
B1 <- get.adjacency(g1)
class(B1)
object.size(B1)
all.equal(B, as(as(B1, "dgTMatrix"), "symmetricMatrix"))
```

```{r}
c1 <- clusters(g1)
c1$no == res$nc
all.equal(c1$membership, res$comp.id)
all.equal(c1$csize, c(table(res$comp.id)), check.attributes=FALSE)
```

```{r}
W <- as(nb2listw(col2, style="W", zero.policy=TRUE), "CsparseMatrix")
g1W <- graph.adjacency(W, mode="directed", weighted="W")
c1W <- clusters(g1W)
all.equal(c1W$membership, res$comp.id)
```


```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

